siteName: Bear Lake Camp
logoPath: /images/logo/BLC-Logo-compass-whiteletters-no-background-small.png
logoAlt: Bear Lake Camp
contactEmail: info@bearlakecamp.org
contactPhone: "(260) 799 5988"
contactAddress: 1805 S 16th St, Albion, IN 46701
registrationUrl: "https://www.ultracamp.com/clientlogin.aspx?idCamp=268"
donationUrl: "https://www.ultracamp.com/donation.aspx?idCamp=268&campCode=blc"
emailFromName: Bear Lake Camp Website
facebookUrl: "https://www.facebook.com/search/top?q=bear%20lake%20camp"
instagramUrl: "https://www.instagram.com/bearlakecamp/"
youtubeUrl: "https://www.youtube.com/channel/UCiw_MKtM5hN83IghEjydmGw?view_as=subscriber"
spotifyUrl: "https://open.spotify.com/playlist/1Dw4cfs5pj7p95uy2f3b0k?si=eZ6NDfybSsGG14DjJ-wXKA"
mapsUrl: "https://maps.app.goo.gl/E6QLKhbminUxho1c8"
